// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.droidit.blog.checkin.model;

import eu.droidit.blog.checkin.model.CheckinUserIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CheckinUserIntegrationTest_Roo_Configurable {
    
    declare @type: CheckinUserIntegrationTest: @Configurable;
    
}
